package tf

import (
	"path/filepath"

	"github.com/activatedio/gen"
	"github.com/dave/jennifer/jen"
)

// GeneratedBy is the source identifier in the "Code generated by ... DO NOT
// EDIT." header of every emitted file.
const GeneratedBy = "github.com/activatedio/tfinfra"

// FileMain is the file-handler key for one entry's generated file. Consumers
// can register additional file handlers against it (via
// Registry.WithHandlerEntries) to append code to the same file without
// forking the library.
type FileMain struct {
	Spec  *Spec
	Entry Entry
}

// NewRegistry returns a gen.Registry loaded with tfinfra's handlers. The
// consumer's gen/main.go typically calls
//
//	tf.NewRegistry().RunDirectoryPathHandler("../internal/generated", &tf.Spec{...})
func NewRegistry() gen.Registry {
	return gen.NewRegistry().WithHandlerEntries(
		gen.NewHandlerEntries().
			AddDirectoryHandler(gen.NewKey[*Spec](), specDirectoryHandler).
			AddFileHandler(gen.NewKey[*FileMain](), fileMainHandler),
	)
}

// specDirectoryHandler owns the target directory: one <entity>_gen.go per
// entry that declares a Resource.
func specDirectoryHandler(dirPath string, r gen.Registry, entry any) {

	spec := entry.(*Spec)

	for _, e := range spec.Entries {
		if !HasImplementation[Resource](e) {
			continue
		}
		path := filepath.Join(dirPath, toSnake(entityType(e).Name())+"_gen.go")
		fm := &FileMain{Spec: spec, Entry: e}
		gen.WithFile(spec.Package, path, func(f *jen.File) {
			r.RunFileHandler(f, fm)
		}, gen.WithGeneratedBy(GeneratedBy))
	}
}

// fileMainHandler composes the sections of one entry's file: the resource
// schema and the plan/state model with proto conversions. CRUD glue emitters
// follow in a later task.
func fileMainHandler(f *jen.File, _ gen.Registry, entry any) {

	fm := entry.(*FileMain)

	res, _ := GetImplementation[Resource](fm.Entry)
	fields := NormalizeFields(fm.Entry, res)

	writeResourceSchema(f, fm.Entry, res, fields)
	writeModel(f, fm.Entry, res, fields)
}
