package tf

import (
	"fmt"
	"path/filepath"

	"github.com/activatedio/gen"
	"github.com/dave/jennifer/jen"
)

// GeneratedBy is the source identifier in the "Code generated by ... DO NOT
// EDIT." header of every emitted file.
const GeneratedBy = "github.com/activatedio/tfinfra"

// FileMain is the file-handler key for one entry's generated file. Consumers
// can register additional file handlers against it (via
// Registry.WithHandlerEntries) to append code to the same file without
// forking the library.
type FileMain struct {
	Spec  *Spec
	Entry Entry
}

// NewRegistry returns a gen.Registry loaded with tfinfra's handlers. The
// consumer's gen/main.go typically calls
//
//	tf.NewRegistry().RunDirectoryPathHandler("../internal/generated", &tf.Spec{...})
func NewRegistry() gen.Registry {
	return gen.NewRegistry().WithHandlerEntries(
		gen.NewHandlerEntries().
			AddDirectoryHandler(gen.NewKey[*Spec](), specDirectoryHandler).
			AddFileHandler(gen.NewKey[*FileMain](), fileMainHandler),
	)
}

// specDirectoryHandler owns the target directory: one <entity>_gen.go per
// entry that declares a Resource, plus index_gen.go with the registration
// slices.
func specDirectoryHandler(dirPath string, r gen.Registry, entry any) {

	spec := entry.(*Spec)

	for _, attr := range sortedKeys(spec.ScopeReferences) {
		validateReference("ScopeReferences."+attr, spec.ScopeReferences[attr])
	}

	for _, e := range spec.Entries {
		validateEntry(e)
		if !HasImplementation[Resource](e) && !HasImplementation[ConfigDataSource](e) {
			continue
		}
		path := filepath.Join(dirPath, toSnake(entityType(e).Name())+"_gen.go")
		fm := &FileMain{Spec: spec, Entry: e}
		gen.WithFile(spec.Package, path, func(f *jen.File) {
			r.RunFileHandler(f, fm)
		}, gen.WithGeneratedBy(GeneratedBy))
	}

	gen.WithFile(spec.Package, filepath.Join(dirPath, "index_gen.go"), func(f *jen.File) {
		writeIndex(f, spec)
	}, gen.WithGeneratedBy(GeneratedBy))
}

// validateEntry panics on a marker combination the generator cannot
// honour: each rule is a condition that must not hold, and what to say.
func validateEntry(e Entry) {

	res, hasResource := GetImplementation[Resource](e)

	rules := []struct {
		broken bool
		msg    string
	}{
		{HasImplementation[DataSourceList](e) && !hasResource,
			"DataSourceList requires a Resource marker on the same entry"},
		{HasImplementation[DataSource](e) && !hasResource,
			"DataSource currently requires a Resource marker on the same entry"},
		{res.Mint != nil && HasImplementation[DataSource](e),
			"a minted resource takes no singular DataSource; its model carries once-only attributes no read has (DataSourceList is fine)"},
		{HasImplementation[ConfigDataSource](e) && hasResource,
			"ConfigDataSource and Resource are mutually exclusive on one entry"},
		{len(Associations(e)) > 0 && !hasResource,
			"Associate requires a Resource marker on the same entry"},
	}

	for _, r := range rules {
		if r.broken {
			panic(fmt.Sprintf("%s: %s", entityType(e).Name(), r.msg))
		}
	}
}

// fileMainHandler composes the sections of one entry's file: schema(s), the
// plan/state model with proto conversions and accessors, the shared crud
// factory, the resource glue, and (when marked) the singular data source.
func fileMainHandler(f *jen.File, _ gen.Registry, entry any) {

	fm := entry.(*FileMain)

	if cds, ok := GetImplementation[ConfigDataSource](fm.Entry); ok {
		fields := NormalizeConfigFields(fm.Entry, cds)
		n := namesFor(fm.Entry, Resource{})
		writeConfigDataSourceSchema(f, fm.Entry, cds, fields, referenceExamples(fm.Spec))
		writeConfigModel(f, fm.Entry, fields, n.Model)
		writeConfigDataSource(f, fm.Entry, n)
		return
	}

	res, _ := GetImplementation[Resource](fm.Entry)
	fields := NormalizeFields(fm.Entry, res)
	cm := AnalyzeClient(fm.Entry, res)
	cm.Mint = AnalyzeMint(fm.Entry, res, fields)
	n := namesFor(fm.Entry, res)
	n.Examples = referenceExamples(fm.Spec)
	n.ScopeRefs = fm.Spec.ScopeReferences
	for _, fd := range fields {
		if fd.ParentID {
			n.ParentAttributes = append(n.ParentAttributes, fd.TfName())
		}
	}
	checkIDAttribute(n, res, fields)

	writeResourceSchema(f, fm.Entry, res, n, fields)
	writeModel(f, fm.Entry, res, n, fields)
	writeCrudFactory(f, fm.Entry, res, cm, n)
	writeResource(f, fm.Entry, n)

	if HasImplementation[DataSource](fm.Entry) {
		writeDataSourceSchema(f, fm.Entry, res, n, fields)
		writeDataSource(f, fm.Entry, n)
	}

	if dsl, ok := GetImplementation[DataSourceList](fm.Entry); ok {
		if cm.List == nil {
			panic(fmt.Sprintf("%s: DataSourceList needs the client's List%s RPC", n.Entity, pluralizeClient.Plural(n.Entity)))
		}
		writeListDataSource(f, fm.Entry, res, n, listNamesFor(n, dsl), fields)
	}

	for _, a := range Associations(fm.Entry) {
		am := AnalyzeAssociation(fm.Entry, res, a)
		writeAssociationFactory(f, res, n, am)
		writeAssociationResource(f, n, am)
	}
}

// checkIDAttribute panics when the resource's own id attribute shares a
// name with another of its attributes: a parent identifier, a proto field,
// or a minted resource's own. One would silently shadow the other in the
// schema. An IDField is a proto field by design, and NormalizeFields has
// already refused one that is also a parent identifier.
func checkIDAttribute(n entityNames, res Resource, fields []Field) {

	if n.IDAttribute == "" || n.IDField {
		return
	}

	taken := map[string]string{}
	for _, attr := range res.Scope.IdentifierAttributes() {
		taken[attr] = "a parent identifier"
	}
	for _, fd := range fields {
		taken[fd.TfName()] = "a field"
	}
	for _, a := range mintAttributes(res) {
		taken[a.name] = "a minted resource's attribute"
	}

	if what, ok := taken[n.IDAttribute]; ok {
		panic(fmt.Sprintf("%s: its id attribute %q collides with %s of the same name; set TypeName to rename the resource", n.Entity, n.IDAttribute, what))
	}
}

// writeIndex emits the registration slices the provider hands to the
// framework.
func writeIndex(f *jen.File, spec *Spec) {

	var resources, dataSources []jen.Code

	for _, e := range spec.Entries {
		if res, ok := GetImplementation[Resource](e); ok {
			n := namesFor(e, res)
			resources = append(resources, jen.Id("New"+n.Entity+"Resource"))
			if HasImplementation[DataSource](e) {
				dataSources = append(dataSources, jen.Id("New"+n.Entity+"DataSource"))
			}
			if dsl, ok := GetImplementation[DataSourceList](e); ok {
				dataSources = append(dataSources, jen.Id("New"+listNamesFor(n, dsl).Plural+"DataSource"))
			}
			for _, a := range Associations(e) {
				am := AnalyzeAssociation(e, res, a)
				resources = append(resources, jen.Id("New"+am.Combined+"Resource"))
			}
		}
		if HasImplementation[ConfigDataSource](e) {
			dataSources = append(dataSources, jen.Id("New"+namesFor(e, Resource{}).Entity+"DataSource"))
		}
	}

	f.Commentf("Resources returns the generated resource constructors for provider registration.")
	f.Func().Id("Resources").Params().Index().Func().Params().Qual(pkgResource, "Resource").Block(
		jen.Return(jen.Index().Func().Params().Qual(pkgResource, "Resource").Values(resources...)),
	)

	f.Commentf("DataSources returns the generated data source constructors for provider registration.")
	f.Func().Id("DataSources").Params().Index().Func().Params().Qual(pkgDatasource, "DataSource").Block(
		jen.Return(jen.Index().Func().Params().Qual(pkgDatasource, "DataSource").Values(dataSources...)),
	)
}
