package tf

import (
	"fmt"
	"path/filepath"

	"github.com/activatedio/gen"
	"github.com/dave/jennifer/jen"
)

// GeneratedBy is the source identifier in the "Code generated by ... DO NOT
// EDIT." header of every emitted file.
const GeneratedBy = "github.com/activatedio/tfinfra"

// FileMain is the file-handler key for one entry's generated file. Consumers
// can register additional file handlers against it (via
// Registry.WithHandlerEntries) to append code to the same file without
// forking the library.
type FileMain struct {
	Spec  *Spec
	Entry Entry
}

// NewRegistry returns a gen.Registry loaded with tfinfra's handlers. The
// consumer's gen/main.go typically calls
//
//	tf.NewRegistry().RunDirectoryPathHandler("../internal/generated", &tf.Spec{...})
func NewRegistry() gen.Registry {
	return gen.NewRegistry().WithHandlerEntries(
		gen.NewHandlerEntries().
			AddDirectoryHandler(gen.NewKey[*Spec](), specDirectoryHandler).
			AddFileHandler(gen.NewKey[*FileMain](), fileMainHandler),
	)
}

// specDirectoryHandler owns the target directory: one <entity>_gen.go per
// entry that declares a Resource, plus index_gen.go with the registration
// slices.
func specDirectoryHandler(dirPath string, r gen.Registry, entry any) {

	spec := entry.(*Spec)

	for _, e := range spec.Entries {
		validateEntry(e)
		if !HasImplementation[Resource](e) {
			continue
		}
		path := filepath.Join(dirPath, toSnake(entityType(e).Name())+"_gen.go")
		fm := &FileMain{Spec: spec, Entry: e}
		gen.WithFile(spec.Package, path, func(f *jen.File) {
			r.RunFileHandler(f, fm)
		}, gen.WithGeneratedBy(GeneratedBy))
	}

	gen.WithFile(spec.Package, filepath.Join(dirPath, "index_gen.go"), func(f *jen.File) {
		writeIndex(f, spec)
	}, gen.WithGeneratedBy(GeneratedBy))
}

func validateEntry(e Entry) {

	if HasImplementation[DataSourceList](e) {
		panic(fmt.Sprintf("%s: DataSourceList is not yet supported", entityType(e).Name()))
	}
	if HasImplementation[DataSource](e) && !HasImplementation[Resource](e) {
		panic(fmt.Sprintf("%s: DataSource currently requires a Resource marker on the same entry", entityType(e).Name()))
	}
}

// fileMainHandler composes the sections of one entry's file: schema(s), the
// plan/state model with proto conversions and accessors, the shared crud
// factory, the resource glue, and (when marked) the singular data source.
func fileMainHandler(f *jen.File, _ gen.Registry, entry any) {

	fm := entry.(*FileMain)

	res, _ := GetImplementation[Resource](fm.Entry)
	fields := NormalizeFields(fm.Entry, res)
	cm := analyzeClient(fm.Entry, res)
	n := namesFor(fm.Entry, res)

	writeResourceSchema(f, fm.Entry, res, fields)
	writeModel(f, fm.Entry, res, fields)
	writeCrudFactory(f, fm.Entry, res, cm, n)
	writeResource(f, fm.Entry, n)

	if HasImplementation[DataSource](fm.Entry) {
		writeDataSourceSchema(f, fm.Entry, res, fields)
		writeDataSource(f, fm.Entry, n)
	}
}

// writeIndex emits the registration slices the provider hands to the
// framework.
func writeIndex(f *jen.File, spec *Spec) {

	var resources, dataSources []jen.Code

	for _, e := range spec.Entries {
		if res, ok := GetImplementation[Resource](e); ok {
			n := namesFor(e, res)
			resources = append(resources, jen.Id("New"+n.Entity+"Resource"))
			if HasImplementation[DataSource](e) {
				dataSources = append(dataSources, jen.Id("New"+n.Entity+"DataSource"))
			}
		}
	}

	f.Commentf("Resources returns the generated resource constructors for provider registration.")
	f.Func().Id("Resources").Params().Index().Func().Params().Qual(pkgResource, "Resource").Block(
		jen.Return(jen.Index().Func().Params().Qual(pkgResource, "Resource").Values(resources...)),
	)

	f.Commentf("DataSources returns the generated data source constructors for provider registration.")
	f.Func().Id("DataSources").Params().Index().Func().Params().Qual(pkgDatasource, "DataSource").Block(
		jen.Return(jen.Index().Func().Params().Qual(pkgDatasource, "DataSource").Values(dataSources...)),
	)
}
